// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Project struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	RootPath  string       `json:"root_path"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Version struct {
	ID          int64         `json:"id"`
	ProjectID   sql.NullInt64 `json:"project_id"`
	VersionPath string        `json:"version_path"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}
